
name: GeneratePDF

on:
  push:
    branches:
      - main

jobs:
  generatePdf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - run: rm package.json package-lock.json && npm init -y
      - name: Install NPM dependencies
        run: npm install @actions/core @actions/github puppeteer

      - name: Generate & Update PDF
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: node github-action/generatePdfAction.js
