name: GeneratePDF

on:
  push:
    branches:
      - dev

jobs:
  generatePdf:
    runs-on: ubuntu-18.04

    steps:
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Generate PDF Action
        uses: ashuvssut/generatePdf-GHA@main
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
