name: GeneratePDF

on:
  push:
    branches:
      - dev

jobs:
  generatePdf:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Generate PDF Action
        uses: ashuvssut/generatePdf-GHA@2a4fb71e452cf73e3c3125030677bdc3e6ccdd3f
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
