name: GeneratePDF

on:
  push:
    branches:
      - dev

jobs:
  generatePdf:
    runs-on: ubuntu-latest

    steps:

      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Generate PDF Action
        uses: ashuvssut/generatePdf-GHA@03511d646536bee85521bb950a150b3ffd6ae17b
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
